<?php

$lang = array(
    "drap" => "france.png",
    "title" => "Jolie Balade",
    "lien1" => "Accueil",
    "lien2" => "Histoire",
    "lien3" => "Appication",
    "lien4" => "Newsletter",
    "btnnav" => "S'inscrire sur liste d'attente",
    "titre1" => "L’organisateur de rencontres à l’étranger.",
    "texte1" => "Echangez avec des célibataires du monde entier et préparez vous à vivre des moments inoubliables. L’amour n’a aucune frontière alors lancez vous ! Créez votre profil selon vos centres d'intérêts, créez des liens avec des étrangers et laissez nous organiser vos dates dans les plus beaux endroits du monde.",
    "textvideo" => "“ Faites de chaques histoire d’amour,une véritable aventure ”",
    "textbtn" => "S’inscrire sur liste d’attente",
    "story" => "Histoire.",
    "textstory" => "Nous avons été conditionnées par les sites de rencontres à être attirés par des gens à proximité car cela représente la facilité, c'est plus simple et plus accessible, mais moi je n'ai jamais vraiment aimé cette idée, mes relations amoureuses ont toujours été chaotique parce que j’avais l’impression constante de ne pas être avec la bonne personne, jusqu’à ce que je me rende compte que je ne cherchais juste pas au bon endroit Lors du premier confinement, j’ai fréquenté beaucoup d’applications de rencontres. J'habitais dans une petite ville du sud de la France à l’époque, et comme beaucoup de gens au vu de la situation à ce moment-là, j'avais envie d'évasion, d'aventures et surtout de rencontrer du monde. En passant du temps sur ces applications de rencontres à la recherche de profils compatibles, j’ai constaté que le centre d'intérêt “Voyage” revenait souvent sous les profils. J’ai donc décidé à partir de là, de compter sa récurrence, et sur 547 profils trouvés, ce centre d'intérêt est revenu 412 fois soit 3 profils sur 4 avaient ce centre d'intérêt. Je me suis donc dit : pourquoi l'amour serait forcément à une dizaine de kilomètres de chez moi ? Le monde est si vaste et il y a tellement de choses à découvrir ensemble. C'est pour cette raison que j’ai décidé de créer joliebalade » Notre nom rappelle un bout de chemin ensemble, une aventure à partager et une belle histoire à raconter. Au-delà de la rencontre amoureuse, nous souhaitons partager nos valeurs et donner l’opportunité à tout le monde de pouvoir voyager et profiter de ce que ce monde a de plus beau à offrir. Notre but est de vous proposer une expérience inédite et de vous offrir un service d’accompagnement premium et unique pour vos rencontres amoureuses.",
    "signature" => "Fondateur de joliebalade.",
    "titrecarte" => "Rencontrez des célibataires partout à travers le monde.",
    "services" => "Nos services.",
    "textservice" => "Avant le décollage, sélectionnez et ajoutez les services que vous souhaitez que l’on s’occupe pour faciliter votre rencontre et la rendre vraiment unique.",
    "bloc1" => "Champagne à votre arrivée",
    "bloc2" => "Chauffeur",
    "bloc3" => "Enrigistrement du vol",
    "bloc4" => "Rapatriement",
    "bloc5" => "Guide touristique",
    "bloc6" => "Baggages supplémentaires",
    "bloc7" => "Disponible 24/24",
    "bloc8" => "Assurance",
    "partners" => "Affiliations.",
    "titreapp" => "Applications.",
    "Manetextapp" => "Nos fonctionnalités",
    "text1app" => "Après avoir rempli toutes les  conditions nécessaires, vous  aurez la possibilité de demander  à voyager pour rencontrer votre  interlocuteur.",
    "text2app" => "Après avoir rempli toutes les  conditions nécessaires, vous  aurez la possibilité de demander  à voyager pour rencontrer votre  interlocuteur.",
    "text3app" => "Après avoir rempli toutes les  conditions nécessaires, vous  aurez la possibilité de demander  à voyager pour rencontrer votre  interlocuteur.",
    "text4app" => "Après avoir rempli toutes les  conditions nécessaires, vous  aurez la possibilité de demander  à voyager pour rencontrer votre  interlocuteur.",
    "titrecom" => "Ils nous adorent déjà.",
    "com1" => "Pré-inscription faite ! Hors de question de rater le lancement de quelque chose d’aussi énorme. Mon premier rendez vous de rêve avec un bel étranger organisé par une application de rencontre? Je signe direct ! 😍",
    "com2" => "Je suis un grand utilisateur d’app de rencontres et je peux affirmer que rien de tel n’existe actuellement sur le marché. Je suis tellement hype que je me suis pré-inscrit en attendant la sortie de l’app 😁😁😁😁",
    "com3" => "C’est vraiment un concept génial ! J’ai toujours pensé que l’homme de ma vie ne se trouvait probablement pas autour de chez moi. J’ai vraiment hâte d’utiliser l’appli !",
    "titrenews" => "Abonnez vous à notre Newsletter",
    "btnnews" => "Soumettre"
);
?>